
import ToastProvider from "@/components/ToastProvider";
import "./globals.css";



export const metadata = {
  title: "Market Mate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
