
import ToastProvider from "@/components/ToastProvider";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";



export const metadata = {
  title: "Market Mate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen h-full text-slate-200">
        <ToastProvider>
          <Navbar/>
          {children}
          <Footer/>
        </ToastProvider>
      </body>
    </html>
  );
}
